version: "3"

services:
  node:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /home/node/app
    tty: true
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      HOST: 0.0.0.0
    container_name: node
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    # command: "yarn start"
    command: sh -c "cd /home/node/app && yarn install && yarn run dev"
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

